### ISSUE TITLE
Incompatibility with actual version of psutil

### ISSUE THREAD

**Issue by maxibor** [quwubin/MFEprimer#2]
It seems that the syntax of psutil has changed.
When running IndexDb.sh I got following the error 
```
Begin indexing ...
Step 1/3: UniFasta done.
Step 2/3: faToTwoBit done.
Step 3/3: Index begin ...
0
Traceback (most recent call last):
  File "/home/maxime/1_MFEprimer/MFEprimer/chilli/mfe_index_db.py", line 227, in <module>
    main()
  File "/home/maxime/1_MFEprimer/MFEprimer/chilli/mfe_index_db.py", line 224, in main
    index(options.filename, options.k)
  File "/home/maxime/1_MFEprimer/MFEprimer/chilli/mfe_index_db.py", line 196, in index
    memory_percent = get_memory_percent()
  File "/home/maxime/1_MFEprimer/MFEprimer/chilli/mfe_index_db.py", line 54, in get_memory_percent
    return p.get_memory_percent()
AttributeError: 'Process' object has no attribute 'get_memory_percent'
Step 3/3: Index done
```

Changing `return p.get_memory_percent()` by `return p.memory_percent()`at line 54 of `mfe_index_db.py` is fixing it.

See : [This link](http://pythonhosted.org/psutil/index.html?highlight=memory_percent#psutil.Process.memory_percent)

**Comment by quwubin** [comment]
Thanks, it has been fixed.
